M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-08-15T15:16:13-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-15T15:16:13-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X4.3661Y-3.7539
X4.3661Y-4.2224
M30
